# Documentation:  http://docs.travis-ci.com/user/languages/julia/
language: julia
os: linux
julia:
  - 1.5.3
  - nightly
git:
  depth: 99999999  
notifications:
  email: false
before_script:
  - julia -e 'if VERSION < v"1.3"; import Pkg; Pkg.add("OrderedCollections"); end'
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())  # Documentation: http://docs.travis-ci.com/user/languages/julia/
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
