name = "NamedTupleTools"
uuid = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
keywords = ["Julia", "NamedTuples"]
license = "MIT"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
version = "0.14.2"

[compat]
julia = "1.6, 1.7, 1.8, 1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
