authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
name = "NamedTupleTools"
uuid = "86c415f0-bb27-11e8-1626-49a490d60138"
license = "MIT"
version = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
